apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: timescaledb:5432
    user: postgres
    database: wikistream
    basicAuth: false
    isDefault: true
    jsonData:
      postgresVersion: 903
      timescaledb: true
      sslmode: disable
    secureJsonData:
      password: password
    version: 1
    editable: false
